package org.akkord.lib

enum class AdFormat { Interstitial, RewardedVideo }

const val EVENT_INTERSTITIAL_LOADED = 1
const val EVENT_INTERSTITIAL_OPENED = 2
const val EVENT_INTERSTITIAL_CLOSED = 3
const val EVENT_INTERSTITIAL_FAILED_TO_LOAD = 4
const val EVENT_INTERSTITIAL_LEFTAPPLICATION = 5
const val EVENT_INTERSTITIAL_FAILED_TO_SHOW = 6

const val EVENT_REWARDEDVIDEO_LOADED = 101
const val EVENT_REWARDEDVIDEO_OPENED = 102
const val EVENT_REWARDEDVIDEO_CLOSED = 103
const val EVENT_REWARDEDVIDEO_FAILED_TO_LOAD = 104
const val EVENT_REWARDEDVIDEO_LEFTAPPLICATION = 105
const val EVENT_REWARDEDVIDEO_STARTED = 106
const val EVENT_REWARDEDVIDEO_COMPLETED = 107
const val EVENT_REWARDEDVIDEO_REWARDED = 108
const val EVENT_REWARDEDVIDEO_FAILED_TO_SHOW = 109
