#!/bin/bash

export AKKORSDK_POD_TARGET=13.0

export AKKORSDK_POD_GOOGLE_MOBILE_ADS_SDK_VERSION=11.5.0
export AKKORSDK_POD_YANDEX_MOBILE_ADS_SDK_VERSION=7.0.1
export AKKORSDK_POD_YANDEX_MOBILE_ADS_INSTREAM_VERSION=0.27.0